version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12 #

    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/jonas747/yagpdb

    # environment: # environment variables for the build itself
      # TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      # - run: mkdir -p $TEST_RESULTS # create the test results directory

      - restore_cache: # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      # Normally, this step would be in a custom primary image;
      # we've added it here for the sake of explanation.
      # - run: go get github.com/lib/pq
      # - run: go get github.com/mattes/migrate
      # - run: go get github.com/jstemmer/go-junit-report

      #  CircleCi's Go Docker image includes netcat
      #  This allows polling the DB port to confirm it is open before proceeding
      # - run:
      #     name: Waiting for Postgres to be ready
      #     command: |
      #       for i in `seq 1 10`;
      #       do
      #         nc -z localhost 5432 && echo Success && exit 0
      #         echo -n .
      #         sleep 1
      #       done
      #       echo Failed waiting for Postgres && exit 1

      - run: git clone -b dgofork https://github.com/jonas747/dutil /go/src/github.com/jonas747/dutil
      - run: git clone -b dgofork https://github.com/jonas747/dshardmanager /go/src/github.com/jonas747/dshardmanager

      - run: go get -d ./..
      - run: go get -v -t github.com/jonas747/yagpdb/cmd/yagpdb # pull and build dependencies for the project
      - run: go get -v -t github.com/jonas747/yagpdb/cmd/shardorchestrator # pull and build dependencies for the project
      - run: go get -v -t github.com/jonas747/yagpdb/cmd/capturepanics # pull and build dependencies for the project

      - run: go test -v ./...

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: /go/src/github.com/jonas747/yagpdb/cmd/yagpdb
          destination: misc

      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: /go/bin/
          destination: binaries